name: Aicomi-Translation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: dev

    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build
      run: |
        cd tools
        msbuild Aicomi-Translation-Tools.sln -t:restore
        msbuild Aicomi-Translation-Tools.sln -t:build -property:Configuration=Release

    - name: ReleaseTool
      run: |
        cd tools\bin\ReleaseTool
        .\ReleaseTool ..\..\..
      continue-on-error: true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Aicomi-Translation
        path: tools\bin\ReleaseTool
        retention-days: 1
